# -*- coding: utf-8 -*-

GLOVELEN=50
GLOVEPATH='resources/glove.6B.50d.txt'
#GLOVEPATH='data/glove.6B.100d.txt'
##
#QPATH='data/jacana/Train1-100.Question.POSInput'
#APATH1='data/jacana/Train1-100.Positive-J.POSInput'
#APATH0='data/jacana/Train1-100.Negative-T.POSInput'
QPATH='data/Qtrain.txt'
APATH1='data/Ptrain.txt'
APATH0='data/Ntrain.txt'
CPATH1="data/Clues1train.txt"
CPATH0="data/Clues0train.txt"
#QPATH='data/jacana/Train1-2393.Question.POSInput'
#APATH1='data/jacana/Train1-2393.Positive-M.POSInput'
#APATH0='data/jacana/Train1-2393.Negative-M.POSInput'
#TQPATH='data/jacana/Test.Question.POSInput'
#TAPATH1='data/jacana/Test.Positive-J.POSInput'
#TAPATH0='data/jacana/Test.Negative-T.POSInput'
TQPATH='data/Qtest.txt'
TAPATH1='data/Ptest.txt'
TAPATH0='data/Ntest.txt'
APATH0='data/Ntrain.txt'
TCPATH1="data/Clues1test.txt"
TCPATH0="data/Clues0test.txt"

#GLOVEPATH='data/w2v.txt'
GLOVEPATH2='data/usedembed.txt'
TGLOVEPATH2='data/tusedembed.txt'
PTQA='data/tqarray.txt'
PTA1A='data/ta1rray.txt'
PTA0A='data/ta0rray.txt'
PTANS1='data/tans1.txt'
PTANS0='data/tans0.txt'
PQA='data/qarray.txt'
PA1A='data/a1rray.txt'
PA0A='data/a0rray.txt'
PANS1='data/ans1.txt'
PANS0='data/ans0.txt'
LISTPATH="data/trainlist.p"
TLISTPATH="data/testlist.p"
